server:
  port: 8081
  shutdown: graceful
spring:
  application:
    name: storebuilder
  data:
    mongodb:
      database: storebuilder
      uri: mongodb+srv://<username>:<password>@<domain>/<database>?retryWrites=true&w=majority
  cloud:
    vault:
      host: localhost
      port: 8200
      authentication: TOKEN
      token: "hvs.DpW7tWuNGWGNPPL99o8rfzYx"
      scheme: http
  config:
    import: vault://